### ISSUE TITLE
questions on beam_search method

### ISSUE THREAD

**Issue by gitfourteen** [pcyin/pytorch_basic_nmt#3]
Can someone explain why use / here? We can not guarantee pre_hyp_ids an integer. Why not use // instead?

IS THIS A TYPO?

`prev_hyp_ids = top_cand_hyp_pos / len(self.vocab.tgt)`
https://github.com/pcyin/pytorch_basic_nmt/blob/master/nmt.py#L340

And I would update my understanding on **_pre_hyp_ids_**. It is a list of at most **_beam_size_** indices that locate where the **top-k** scours belong, i.e., the indices of **_hypotheses_**, for every beam search step. The items of  _**pre_hyp_ids**_ may have repetitive ones.

for example, set **_beam_size = 4_**, in previous beam search step, we have already got 1 sentence for **_completed_hypotheses_**, and
`hypotheses = [['<s>',word_1, word_2],['<s>',word_3, word_4], ['<s>',word_5, word_6] ]`

We then find the **top 2** words following word_2, and **the third highest** word following word_6, then we have
`pre_hyp_ids = [0, 0, 2]`

How to get this result?
We further assume these 3 words are the **100th, 1,000th, 9,000th** words in the vocabulary, 
and the length of the vocabulary is **50000**

```
top_cand_hyp_pos =  [100, 1000, 9000+2*50000]
pre_hyp_ids = [100, 1000, 9000+2*50000] // 50000 = [0, 0, 2]
```

**Comment by gitfourteen** [comment]
and if I was right, the beam search here simply sorted the sum of scores of the candidate sentences to get the final choice. It did not normalize the score with sentence lengths. Is this just for teaching purpose so that students can optimize base on this?

`top_hypotheses = [hyps[0] for hyps in hypotheses]`
https://github.com/pcyin/pytorch_basic_nmt/blob/master/nmt.py#L755

**Comment by gitfourteen** [comment]
> Can someone explain why use / here? We can not guarantee pre_hyp_ids an integer. Why not use // instead?
> 
> IS THIS A TYPO?
> 
> `prev_hyp_ids = top_cand_hyp_pos / len(self.vocab.tgt)`
> https://github.com/pcyin/pytorch_basic_nmt/blob/master/nmt.py#L340
> 
> And I would update my understanding on **_pre_hyp_ids_**. It is a list of at most **_beam_size_** indices that locate where the **top-k** scours belong, i.e., the indices of **_hypotheses_**, for every beam search step. The items of _**pre_hyp_ids**_ may have repetitive ones.
> 
> for example, set **_beam_size = 4_**, in previous beam search step, we have already got 1 sentence for **_completed_hypotheses_**, and
> `hypotheses = [['<s>',word_1, word_2],['<s>',word_3, word_4], ['<s>',word_5, word_6] ]`
> 
> We then find the **top 2** words following word_2, and **the third highest** word following word_6, then we have
> `pre_hyp_ids = [0, 0, 2]`
> 
> How to get this result?
> We further assume these 3 words are the **100th, 1,000th, 9,000th** words in the vocabulary,
> and the length of the vocabulary is **50000**
> 
> ```
> top_cand_hyp_pos =  [100, 1000, 9000+2*50000]
> pre_hyp_ids = [100, 1000, 9000+2*50000] // 50000 = [0, 0, 2]
> ```

I found the answer for the first question here:
[https://github.com/pytorch/pytorch/issues/5411](url)

Pytorch did not use floor division // as Numpy and Python for NOW.

**Comment by pcyin** [comment]
Hi, the type of `top_cand_hyp_pos` should be `Torch.LongTensor`, so is the `prev_hyp_ids `

**Comment by pcyin** [comment]
Sorry for my late reply! For your second question, note that the shape of `top_cand_hyp_pos` is `number_of_hypotheses * vocab_size`. Therefore, by dividing the size of `top_cand_hyp_pos` with the vocab size, we can get the id of the hypothesis a top-ranked token belongs to
